version: "3.9"
services:
  snmp-backend:
    build: .
    image: snmp-backend:dev
    container_name: snmp-backend
    ports:
      - "5000:5000/tcp"
      - "9162:9162/udp"
    environment:
      APP_ID: default-app-id
      ENABLE_TRAP_RECEIVER: "1"
      TRAP_COMMUNITY: public
      # --- pilih salah satu blok di bawah ---

      # (A) Firestore Production (pakai service account)
      FIREBASE_KEY_PATH: /secrets/serviceAccountKey.json
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/serviceAccountKey.json

      # (B) Firestore Emulator (local) — COMMENT blok (A), UNCOMMENT ini
      # FIRESTORE_EMULATOR_HOST: host.docker.internal:8080

      # CORS untuk frontend local (sesuaikan jika beda port)
      CORS_ORIGINS: http://127.0.0.1:5500,http://localhost:5500
      # SNMP default
      SNMP_TIMEOUT: "1.0"
      SNMP_RETRIES: "1"
      SNMP_PAGE_SIZE: "50"
      DUMMY_MODE: "1" # 0 kalau mau real SNMP
    volumes:
      # Mount key hanya untuk Production Firestore
      - ./serviceAccountKey.json:/secrets/serviceAccountKey.json:ro
    restart: unless-stopped
